/**
 * CP3 executor — the ONLY component that materializes an "executed" decision,
 * and it does so by writing ONE artifact to STAGING. It never touches the live
 * corpus, never calls GitHub, never runs an LLM. reflect() invokes it ONLY for
 * decisions the policy already marked "executed" (autonomous + explicit flag +
 * !dry-run) AND only when a staging root is configured.
 *
 * Containment is re-enforced here, not just upstream: every write re-validates
 * the staging root against the corpus and re-proves the artifact path stays
 * inside staging. All free text is redacted before it hits disk. Any failure,
 * any unexpected action type, any path that fails a guard → `blocked`, and
 * NOTHING is written. There is no code path that writes outside staging.
 */

import { writeFileSync, openSync, closeSync, unlinkSync } from "node:fs";
import { relative, join, dirname } from "node:path";
import matter from "gray-matter";
import { redactSecrets } from "./redact.js";
import {
  validateStagingRoot,
  prepareStagingSubdir,
  safeSlug,
  isSymlink,
  isInside,
  realpathOrNull,
  PROPOSED_NEURONS_SUBDIR,
  ISSUES_SUBDIR,
} from "./staging-paths.js";
import type { ExecutionRecord, PolicyDecision } from "./autonomy-types.js";

export interface ExecutorContext {
  /** Where staged artifacts go. Re-validated here against neuronsDir. */
  stagingRoot: string;
  /** The live corpus — the executor proves it never writes inside this. */
  neuronsDir: string;
  /** Injectable clock for deterministic artifacts/tests. */
  now: Date;
}

export interface ExecutionOutcome {
  status: "executed" | "blocked";
  reason: string;
  /** Present IFF status==="executed". */
  execution?: ExecutionRecord;
}

function blocked(reason: string): ExecutionOutcome {
  return { status: "blocked", reason };
}

function isoDate(now: Date): string {
  return now.toISOString().split("T")[0];
}

/** Render a staged PROPOSED neuron (markdown). All free text redacted. */
function renderProposedNeuron(d: PolicyDecision, now: Date): string {
  const f = d.finding;
  const fm = {
    type: "pattern-memory",
    status: "proposed",
    source: `reflect:${f.dimension}`,
    finding_id: f.id ?? f.dimension,
    created: isoDate(now),
    confidence: f.confidence,
    ids: f.ids,
  };
  const body =
    `\n# PROPOSED NP — ${redactSecrets(d.summary)}\n\n` +
    `> Staged proposal generated by reflect_neurons (CP3 executor). NOT a live neuron.\n` +
    `> Review before promoting; this file lives in staging only.\n\n` +
    `## Evidence\n${f.evidence.map((e) => `- ${redactSecrets(e)}`).join("\n")}\n\n` +
    `## Inference\n${redactSecrets(f.inference)}\n\n` +
    `## Recommendation\n${redactSecrets(f.recommendation)}\n`;
  return matter.stringify(body, fm);
}

/** Render a staged issue artifact (JSON). Title/body redacted. No GitHub I/O. */
function renderIssue(d: PolicyDecision, now: Date): string {
  const f = d.finding;
  const issue = {
    title: redactSecrets(d.summary),
    body: [
      `**Finding** ${f.id ?? f.dimension} (${f.confidence})`,
      ``,
      `**Evidence**`,
      ...f.evidence.map((e) => `- ${redactSecrets(e)}`),
      ``,
      `**Inference**: ${redactSecrets(f.inference)}`,
      ``,
      `**Recommendation**: ${redactSecrets(f.recommendation)}`,
      ``,
      `_Staged by reflect_neurons CP3 executor — not created on GitHub._`,
    ].join("\n"),
    labels: ["dream", "reflect", f.dimension],
    finding_id: f.id ?? f.dimension,
    ids: f.ids,
    source: "reflect_neurons:cp3-executor",
    created_at: now.toISOString(),
  };
  return JSON.stringify(issue, null, 2) + "\n";
}

/**
 * Execute a single decision the policy marked "executed". Returns `executed`
 * with an ExecutionRecord (the staged artifact) or `blocked` with a reason —
 * never throws, never writes outside staging.
 */
export function executeAction(d: PolicyDecision, ctx: ExecutorContext): ExecutionOutcome {
  const t = d.action_type;
  if (t !== "create_issue" && t !== "create_proposed_neuron") {
    return blocked(`executor: unsupported action type '${t}' — only create_issue/create_proposed_neuron`);
  }

  // (1) PHYSICAL containment of the staging root (realpath — symlink-safe).
  const v = validateStagingRoot(ctx.stagingRoot, ctx.neuronsDir);
  if (!v.ok || !v.root || !v.corpus) return blocked(`executor: ${v.reason}`);
  const root = v.root;
  const corpus = v.corpus;

  // (2) Sanitize the slug; a traversal-only id collapses to empty → refuse.
  const slug = safeSlug(d.finding.id ?? d.finding.dimension);
  if (!slug) return blocked(`executor: empty slug after sanitization (id='${d.finding.id ?? d.finding.dimension}')`);

  const subdir = t === "create_proposed_neuron" ? PROPOSED_NEURONS_SUBDIR : ISSUES_SUBDIR;
  const ext = t === "create_proposed_neuron" ? ".md" : ".json";

  // (3) Prepare the subdir: refuse a symlinked subdir, create it, re-realpath it
  //     back inside the real root and outside the real corpus.
  const prep = prepareStagingSubdir(root, corpus, subdir);
  if (!prep.ok || !prep.dir) return blocked(`executor: ${prep.reason}`);
  const path = join(prep.dir, `${slug}${ext}`);

  // (4) The artifact itself must not be a pre-existing symlink, and its parent's
  //     realpath must still be the verified subdir (final write-boundary guard).
  if (isSymlink(path)) return blocked(`executor: artifact path '${slug}${ext}' is a symlink — refused`);
  const parentReal = realpathOrNull(dirname(path));
  if (parentReal == null || (parentReal !== prep.dir && !isInside(root, parentReal))) {
    return blocked(`executor: artifact parent escaped staging root — refused`);
  }
  if (parentReal === corpus || isInside(corpus, parentReal)) {
    return blocked(`executor: artifact parent inside live corpus — refused`);
  }

  const content =
    t === "create_proposed_neuron" ? renderProposedNeuron(d, ctx.now) : renderIssue(d, ctx.now);

  // (5) EXCLUSIVE create (O_CREAT|O_EXCL via "wx"). If ANY directory entry already
  //     exists at this path — a regular file, a symlink, OR a HARDLINK that shares
  //     an inode with a live-corpus file — open() fails atomically with EEXIST and
  //     we refuse. This closes the hardlink/preexisting-artifact bypass: a default
  //     "w" write would truncate-and-overwrite the shared inode, mutating neurons/.
  //     We only ever create-new; we never overwrite. O_EXCL is also TOCTOU-safe.
  let fd: number;
  try {
    fd = openSync(path, "wx", 0o600);
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    return blocked(
      code === "EEXIST"
        ? `executor: artifact '${slug}${ext}' already exists — refusing to overwrite (possible hardlink/symlink into the corpus)`
        : `executor: cannot exclusively create artifact '${slug}${ext}' — ${String(e)}`,
    );
  }
  try {
    writeFileSync(fd, content, "utf-8");
  } catch (e) {
    // Best-effort cleanup: we exclusively created `path`, so a failed write must
    // not leave a partial artifact behind in staging.
    try {
      unlinkSync(path);
    } catch {
      /* best effort — staging only, never the corpus */
    }
    return blocked(`executor: write failed — ${String(e)}`);
  } finally {
    // close must never throw out of executeAction — the contract is "never throws".
    try {
      closeSync(fd);
    } catch {
      /* fd already closed / invalid */
    }
  }

  const artifact = relative(root, path);
  return {
    status: "executed",
    reason: `staged write to ${artifact}`,
    execution: { target: "staging", artifact },
  };
}
