/**
 * Run/trace metadata for CLI report outputs (PR-A — governance/traceability).
 *
 * This describes the RUN (which tool version / source revision produced a report,
 * and when) and is kept SEPARATE from the analysis itself. It is robust by design:
 * a missing `package.json` or an absent/unavailable `git` both degrade to
 * `"unknown"` — `toolMetadata()` never throws. The metadata is attached at the CLI
 * output layer, so the pure report builders (`runProjectCoverage`, `runNoLossGate`)
 * stay unchanged.
 */
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

export interface ToolMetadata {
  /** Package version from the nearest package.json, or "unknown". */
  tool_version: string;
  /** Source git SHA of the running build, or "unknown" if git is unavailable. */
  tool_git_sha: string;
  /** ISO-8601 timestamp of when the report was produced. */
  generated_at: string;
}

/** Path to the package.json that ships with this tool (../package.json from dist/ or src/). */
function packageJsonPath(): string {
  return fileURLToPath(new URL("../package.json", import.meta.url));
}

/**
 * Collect run metadata. `now` is injectable for deterministic tests. Every lookup
 * is best-effort: failures fall back to "unknown" rather than throwing.
 */
export function toolMetadata(now: Date = new Date()): ToolMetadata {
  let tool_version = "unknown";
  let pkgDir = "";
  try {
    const p = packageJsonPath();
    pkgDir = dirname(p);
    const v = (JSON.parse(readFileSync(p, "utf-8")) as { version?: unknown }).version;
    if (typeof v === "string" && v.trim() !== "") tool_version = v;
  } catch {
    /* keep "unknown" */
  }

  let tool_git_sha = "unknown";
  try {
    const out = execFileSync("git", ["rev-parse", "HEAD"], {
      cwd: pkgDir || undefined,
      stdio: ["ignore", "pipe", "ignore"], // never surface git's stderr
    })
      .toString()
      .trim();
    if (out) tool_git_sha = out;
  } catch {
    /* git absent / not a repo → keep "unknown" */
  }

  return { tool_version, tool_git_sha, generated_at: now.toISOString() };
}

/** A one-line Markdown footer carrying the run metadata. */
export function toolMetadataMarkdown(tool: string, m: ToolMetadata): string {
  return `\n---\n_Generated by \`${tool}\` v${m.tool_version} · sha \`${m.tool_git_sha}\` · ${m.generated_at}_\n`;
}
